vscode:
  extensions:
    - connorshea.vscode-ruby-test-adapter@0.6.1:HO9rpcRv7bmRIuo7Mty/zg==
    - hbenl.vscode-test-explorer@2.15.0:koqDUMWDPJzELp/hdS/lWw==

tasks:
  - init: echo "Build"
    command: |
      bundle
      bundle exec jekyll serve

  - test: echo "Testing phase"
    command: |
      bundle exec htmlproofer ./_site --allow-hash-href --check-favicon --check-html --disable-external
      
# Ports to expose on workspace startup (optional)
ports:
  - port: 4000
    onOpen: open-preview
  
