# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Descubriendo a Nuria C. Botey
email: nuriacbotey@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hola, soy @nuriacbotey.  Aquí encontrarás información
  acerca de mí y mis publicaciones.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nuriacbotey
github_username:  nuriacbotey

# Build settings
markdown: kramdown
theme: jekyll-theme-hydejack
plugins:
  - jekyll-feed
  - jekyll-default-layout
  - jekyll-paginate
  - jekyll-twitter-plugin

# Hydejack customization
logo: /assets/img/logo_nuriacbotey_400x400.jpg

# This text will appear in a `<small>` tag in the footer of every page.
copyright:             © 2020. Todos los derechos reservados.

# Pagination configuration (used by the `blog` layout)
paginate:              10
paginate_path:         /page-:num/

# Format of the permalinks
permalink: /:year/:month/:day/:title/

# accent_image: /assets/img/HAL900.jpg
accent_image: /assets/img/efe-kurnaz-RnCPiXixooY-unsplash.jpg
#  background: '#800080' # provide a valid CSS background value
#  overlay:    false     # set to true if you want a dark overlay
font:         "'Roboto Slab', Helvetica, Arial, sans-serif"
font_heading: "'Roboto Slab', Helvetica, Arial, sans-serif"
google_fonts: "Roboto+Slab:700|Noto+Sans:400,400i,700,700i"

# author
author:
  name: Nuria C. Botey
  email: nuriacbotey@gmail.com
  about: |
    Hola, soy @nuriacbotey, aquí encontrarás
    información acerca de mi.

# sidebar
defaults:
  - scope:
      path: paginas/quien_soy.md
    values:
      menu: true
      order: 1
  - scope:
      path: paginas/premios.md
    values:
      menu: true
      order: 2
  - scope:
      path: paginas/publicaciones.md
    values:
      menu: true
      order: 3

# Exclude from processing.
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']

cookies_banner: true

