# Welcome to Jekyll!
#
title: Descubriendo a Nuria C. Botey
email: nuriacbotey@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hola, soy @nuriacbotey.  Aquí encontrarás información
  acerca de mí y mis publicaciones.
twitter_username: nuriacbotey
github_username:  nuriacbotey
logo: /assets/img/logo_nuriacbotey_400x400.jpg

# Authors
author:
  name: Nuria C. Botey
  email: nuriacbotey@gmail.com
  about: |
    Hola, soy @nuriacbotey, aquí encontrarás
    información acerca de mi.

# Build settings
markdown: kramdown
theme: jekyll-theme-hydejack
plugins:
  - jekyll-feed
  - jekyll-default-layout
  - jekyll-paginate
  - jekyll-twitter-plugin

# Google Analytics
google_analytics: UA-124601299-1

# Hydejack customization
accent_image: /assets/img/efe-kurnaz-RnCPiXixooY-unsplash.jpg
font_heading: "'Roboto Slab', Helvetica, Arial, sans-serif"
google_fonts: "Roboto+Slab:700|Noto+Sans:400,400i,700,700i"

# This text will appear in a `<small>` tag in the footer of every page.
copyright:             © 2020. Todos los derechos reservados.

# Format of the permalinks
permalink: /:year/:month/:day/:title/

# Pagination configuration (used by the `blog` layout)
paginate:              10
paginate_path:         /page-:num/

# sidebar
defaults:
  - scope:
      path: paginas/quien_soy.md
    values:
      menu: true
      order: 1
  - scope:
      path: paginas/premios.md
    values:
      menu: true
      order: 2
  - scope:
      path: paginas/publicaciones.md
    values:
      menu: true
      order: 3

# Exclude from processing.
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
